version: "3.8"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        ports: 
            - 27017:27017
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=rootuser
            - MONGO_INITDB_ROOT_PASSWORD=rootpass
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
            - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
            - ME_CONFIG_MONGODB_SERVER=mongodb
    redis:
        container_name: redis
        hostname: redis
        image: redis
        ports:
            - 6379:6379
        restart: always

    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - "8090:8081"
volumes: 
    data: {} 
    
networks:
    default: 
        name: mongodb_network